#!/bin/bash

# Create the scratch org
echo "sfdx force:org:create -s -f config/context-detective-scratch-def.json -a 'context-detective'"
sfdx force:org:create -s -f config/context-detective-scratch-def.json -a 'context-detective'

# Push the project into the org
echo "sfdx force:source:push"
sfdx force:source:push

# Grant the user access to objects and fields
echo "sfdx force:user:permset:assign -n Context_Detective"
sfdx force:user:permset:assign -n Context_Detective

# Run the Detective
echo "sfdx force:apex:execute -f investigate.apex"
sfdx force:apex:execute -f investigate.apex

# Open the Org
echo "sfdx force:org:open -p lightning/o/Context__c/list?filterName=All"
sfdx force:org:open -p lightning/o/Context__c/list?filterName=All